spring.h2.console.enabled=true

# A chave secreta do JWT deve ser fornecida como uma variável de ambiente: EXPLORAJAMPA_APP_JWT_SECRET
# explorajampa.app.jwtSecret=
explorajampa.app.jwtExpirationMs=86400000
